### PR TITLE
Move 'import os' to top so line 810 doesn't trigger an error on Mac/Unix

### PR DESCRIPTION
**Pull request by nschneid**

### CODE REVIEW

**Comment by amir-zeldes** [comment]
This looks harmless so I don't mind merging, but can you tell me what the error was and what Linux OS/python version triggers it? It runs fine on my Red Hat server with Python 2.7 and 3.5.

**Comment by nschneid** [comment]
This was on my Mac. Was that point in the code reached when you tried it?

**Comment by nschneid** [comment]
(There's no version of Python in which `os` gets imported magically. Though there could be some custom environment configuration that does it, I suppose.)

**Comment by amir-zeldes** [comment]
I see it now, sorry, I was testing module usage in Linux, so it didn't get there

**Pull request merged**
